---
title: "Coe College Baseball 2019 Review"
author: "Luke Smailes"
date: "10/23/2019"
output: html_document
   
---


The 2019 season for Coe College Baseball ended with a program record 37 wins and an appearence in the NCAA Super Regional. Dominating both sides of the ball, Coe had 9 total all-conference players, the ARC pitcher of the year, and coach of the year. Aside from the considerable experienced talent that was on the field, the purpose of this paper is to analyize what exactly went right. Even in a year in which we won the conference by a comfortable seven games, there a still areas we can improve on moving forward. Our goal will be to replicate 30+ win seasons even when we lose large contribtors due to graduation.  

A noticeable trait off-the-bat was our strikeout rate improvement. A 3.5% improvement helped to post the best K:BB ratio since 2013. We struckout considerably less than the rest of the conference in 2019, with Wartburg's 15.2% being the second lowest. There were some extreme struggles in the ARC, as Dubuque posted the 7th worst K% of all-time (since 2001) - 19.14% and Nebraska Wesleyan had a conference all-time worst 22%. However, the worst K:BB ratio was held by the conference tournament champion, Buena Vista (2.83). The only ratio better than Coe was Dubuque because of their impressive 13.13% walk rate, compensating for their enormous (19.6%) strikeout rate       
<table class="table table-striped table-hover" style="font-size: 12px; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:center;"> Year </th>
   <th style="text-align:center;"> Team </th>
   <th style="text-align:center;"> K% </th>
   <th style="text-align:center;"> BB% </th>
   <th style="text-align:center;"> K:BB </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:center;"> 2013 </td>
   <td style="text-align:center;"> COE </td>
   <td style="text-align:center;"> 0.12 </td>
   <td style="text-align:center;"> 0.08 </td>
   <td style="text-align:center;"> 1.45 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> 2014 </td>
   <td style="text-align:center;"> COE </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.08 </td>
   <td style="text-align:center;"> 1.82 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> 2015 </td>
   <td style="text-align:center;"> COE </td>
   <td style="text-align:center;"> 0.12 </td>
   <td style="text-align:center;"> 0.07 </td>
   <td style="text-align:center;"> 1.68 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> 2016 </td>
   <td style="text-align:center;"> COE </td>
   <td style="text-align:center;"> 0.14 </td>
   <td style="text-align:center;"> 0.07 </td>
   <td style="text-align:center;"> 1.94 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> 2017 </td>
   <td style="text-align:center;"> COE </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.08 </td>
   <td style="text-align:center;"> 2.10 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> 2018 </td>
   <td style="text-align:center;"> COE </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.08 </td>
   <td style="text-align:center;"> 2.05 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> 2019 </td>
   <td style="text-align:center;"> COE </td>
   <td style="text-align:center;"> 0.12 </td>
   <td style="text-align:center;"> 0.08 </td>
   <td style="text-align:center;"> 1.51 </td>
  </tr>
</tbody>
</table>
The most important aspect for improvement in 2020 is drawing more walks, as our 7.95\% walk rate ranked 7th in the conference. We can see that our walk rate has remained relatively steady over the course of the BBCOR era. The overall offensive difference in 2019 was not only a significant contact rate increase, but also a 33-point increase in BABIP (batting average on balls in play) from .349 to .381. The average BABIP in the BBCOR era is .341.

We can attribute this to three different factors. First, we can look at the league defense and on the surface, it does not seem like this was the biggest contributor. We do not have the capability to construct advanced defensive metrics that might be able to tell us more, but the conference was slightly better defensively in 2019 compared to 2018. There was an average fielding percentage of .954 and 65.3 errors in 2018 and an average of .957 and 60.8 errors in 2019.
 
The next aspect to consider is a better talent level and better quality of contact. With the talented, experienced, and deep lineup that we had, our hard hit percentage was undoubtedly higher. From a philosophical standpoint, focusing on the optimal launch parameters for the D-III game in training looks to have had a beneficial effect. Lower launch angles that put more pressure on the defense to make plays is more sustainable throughout a season at this level, and especially this level in the BBCOR era.

Lastly, the aspect of luck is likely to have contributed to the spike in BABIP. A 45-game season can prevent some of the normal BABIP irregularities from evening out. To protect against this inevitable regression, generating more walks while not sacrificing with swings and misses or looking K's can help close the gap. The only 2 teams with a higher BABIP in the BBCOR era than Coe in 2019 were Dubuque in 2018 and Buena Vista in 2016, both at .386. In 2019, Dubuque cratered to .326 and in 2017, Buena Vista normalized to near the BBCOR mean of .346.

The lack of walks from our top hitters can be seen in their wOBAs, or weighted on-base average. This stat combines all aspects of hitting and weighs them in proportion to their actual run value. We had no players in the top-10 of wOBA for conference starters. Burns and Frazier tied for 12th at .249. While there was not the presence at the top, it was made up with the consistency of the team. Coe led the conference with a .234 wOBA and Evans was the only starter below the league starter average (.216) at .201. This includes position players that started at least 20 games in 2019. Simpson's Truman Schmitt had the highest wOBA at .310 and was almost 20 points ahead of the next closest hitter, Luke Plunkett of Luther. Coe's top-6 hitters were between .243 (Arp) and .249 (Burns & Frazier). Throughout the other 8 conference teams, there were 25 starters with sub-.200 wOBAs. Coe had none.

In the BBCOR era (2011-Present), the 2019 Kohawks scored the 5th most runs in a season (314), only behind 2016 Luther, 2016 Buena Vista, 2015 Coe and 2014 Buena Vista. Individually, we had 3 hitters in the top-10 of wRAA (weighted runs above average). This measures the number of runs a player contributes to his team compared to the average player. This is a counting statistic, so players accrue more (or less) the more they play. This can be thought of as a player's offensive WAR (wins above replacement). A player with a wRAA of 0 would therefore be a replacement level hitter. Table 2 shows the conference's top players in terms of wRAA. Each team is represented in the top-10 with the exception of Loras


```
##    [1] 0.503 0.587 0.474 0.497 0.512 0.462 0.491 0.474 0.470 0.467 0.484
##   [12] 0.478 0.485 0.448 0.437 0.427 0.417 0.422 0.403 0.491 0.389 0.403
##   [23] 0.441 0.440 0.427 0.444 0.359 0.375 0.360 0.403 0.452 0.445 0.378
##   [34] 0.418 0.400 0.359 0.385 0.377 0.376 0.376 0.407 0.361 0.429 0.359
##   [45] 0.328 0.393 0.330 0.306 0.317 0.331 0.357 0.312 0.318 0.262 0.350
##   [56] 0.350 1.000 1.000 0.667 0.667 0.667 0.500 0.500 0.550 0.516 0.520
##   [67] 0.500 0.495 0.473 0.522 0.456 0.396 0.419 0.404 0.348 0.444 0.470
##   [78] 0.333 0.378 0.400 0.433 0.493 0.444 0.463 0.353 0.414 0.500 0.333
##   [89] 0.324 0.378 0.364 0.318 0.364 0.368 0.356 0.417 0.344 0.380 0.347
##  [100] 0.385 0.397 0.363 0.346 0.342 0.357 0.462 0.391 0.344 0.341 0.413
##  [111] 0.344 0.310 0.326 0.304 0.346 0.364 0.348 0.471 0.571 0.250 0.278
##  [122] 0.346 0.344 0.366 0.350 0.260 0.303 0.286 0.319 0.306 0.317 0.333
##  [133] 0.214 0.368 0.294 0.276 0.258 0.340 0.242 0.333 0.275 0.299 0.257
##  [144] 0.207 0.298 0.281 0.258 0.231 0.308 0.281 0.294 0.143 0.500 0.241
##  [155] 0.300 0.167 0.227 0.320 0.300 0.190 0.129 0.118 0.125 0.125 0.000
##  [166] 0.200 0.000 0.000 0.250 0.000 0.000 0.000 0.000 0.400 0.000 0.000
##  [177] 0.500 0.333 0.000 0.000 0.333 0.000 0.000 0.000 0.000 0.000 0.000
##  [188] 0.500 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
##  [199] 0.000 0.000 1.000 1.000 0.800 0.571 0.500 0.500 0.667 0.500 0.442
##  [210] 0.465 0.469 0.417 0.451 0.460 0.571 0.448 0.497 0.442 0.454 0.428
##  [221] 0.417 0.458 0.428 0.435 0.450 0.471 0.438 0.455 0.415 0.398 0.500
##  [232] 0.413 0.417 0.442 0.486 0.465 0.412 0.427 0.417 0.485 0.388 0.409
##  [243] 0.474 0.397 0.454 0.484 0.395 0.427 0.443 0.400 0.455 0.600 0.333
##  [254] 0.447 0.375 0.420 0.389 0.378 0.362 0.418 0.393 0.403 0.417 0.417
##  [265] 0.363 0.405 0.400 0.338 0.398 0.424 0.300 0.355 0.333 0.383 0.360
##  [276] 0.385 0.294 0.384 0.397 0.360 0.375 0.368 0.393 0.327 0.333 0.415
##  [287] 0.360 0.403 0.373 0.347 0.386 0.373 0.355 0.324 0.367 0.385 0.333
##  [298] 0.338 0.341 0.325 0.366 0.396 0.362 0.286 0.341 0.384 0.376 0.361
##  [309] 0.280 0.317 0.366 0.336 0.310 0.327 0.321 0.438 0.400 0.359 0.395
##  [320] 0.345 0.273 0.316 0.362 0.286 0.216 0.324 0.311 0.417 0.364 0.303
##  [331] 0.353 0.278 0.257 0.269 0.325 0.320 0.346 0.270 0.244 0.278 0.333
##  [342] 0.283 0.265 0.258 0.269 0.357 0.237 0.268 0.286 0.167 0.205 0.222
##  [353] 0.360 0.250 0.125 0.222 0.091 0.278 0.091 0.091 0.000 0.000 0.375
##  [364] 0.000 0.000 0.000 0.000 0.000 0.250 0.000 0.000 0.000 0.000 0.000
##  [375] 0.000 0.000 0.333 0.000 0.000 1.000 0.000 0.000 0.000 0.000 0.000
##  [386] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 1.000
##  [397] 1.000 1.000 1.000 0.750 0.700 0.667 0.571 0.571 0.667 0.500 0.500
##  [408] 0.500 0.560 0.429 0.503 0.459 0.542 0.511 0.456 0.400 0.446 0.431
##  [419] 0.452 0.453 0.450 0.416 0.438 0.373 0.443 0.495 0.444 0.429 0.434
##  [430] 0.438 0.408 0.378 0.397 0.459 0.434 0.416 0.375 0.444 0.429 0.448
##  [441] 0.374 0.373 0.383 0.417 0.380 0.447 0.425 0.389 0.488 0.383 0.389
##  [452] 0.399 0.380 0.426 0.379 0.387 0.379 0.368 0.429 0.404 0.372 0.351
##  [463] 0.381 0.375 0.336 0.436 0.333 0.352 0.379 0.378 0.323 0.412 0.385
##  [474] 0.409 0.404 0.339 0.319 0.372 0.333 0.471 0.426 0.366 0.301 0.383
##  [485] 0.340 0.338 0.392 0.372 0.361 0.284 0.316 0.326 0.423 0.303 0.311
##  [496] 0.284 0.351 0.345 0.328 0.291 0.316 0.333 0.324 0.350 0.235 0.372
##  [507] 0.329 0.371 0.323 0.306 0.333 0.222 0.270 0.313 0.270 0.289 0.222
##  [518] 0.273 0.333 0.333 0.200 0.429 0.278 0.400 0.350 0.308 0.255 0.311
##  [529] 0.259 0.267 0.313 0.316 0.167 0.275 0.167 0.200 0.200 0.250 0.250
##  [540] 0.136 0.000 0.182 0.200 0.000 0.125 0.000 0.000 0.000 0.333 0.500
##  [551] 0.000 0.000 0.500 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.500
##  [562] 0.000 0.500 0.000 0.500 0.000 1.000 1.000 1.000 1.000 0.000 0.000
##  [573] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
##  [584] 0.483 0.451 0.500 0.439 0.444 0.441 0.434 0.456 0.457 0.456 0.437
##  [595] 0.404 0.394 0.433 0.397 0.454 0.409 0.429 0.402 0.401 0.403 0.372
##  [606] 0.380 0.398 0.405 0.416 0.432 0.421 0.420 0.352 0.399 0.423 0.406
##  [617] 0.402 0.366 0.368 0.422 0.349 0.358 0.369 0.350 0.380 0.342 0.358
##  [628] 0.348 0.326 0.370 0.339 0.344 0.371 0.305 0.375 0.333 0.371 0.364
##  [639] 0.336 0.267 0.317 0.297 0.314 0.271 0.296 1.000 1.000 1.000 1.000
##  [650] 0.600 0.500 0.500 0.500 0.543 0.455 0.517 0.468 0.538 0.438 0.442
##  [661] 0.417 0.435 0.362 0.367 0.415 0.452 0.429 0.347 0.478 0.444 0.333
##  [672] 0.358 0.350 0.354 0.408 0.388 0.273 0.368 0.346 0.408 0.333 0.333
##  [683] 0.343 0.338 0.333 0.313 0.280 0.400 0.625 0.400 0.325 0.360 0.383
##  [694] 0.267 0.333 0.342 0.300 0.306 0.323 0.222 0.300 0.309 0.260 0.322
##  [705] 0.267 0.304 0.235 0.333 0.326 0.238 0.380 0.388 0.256 0.242 0.300
##  [716] 0.319 0.231 0.176 0.263 0.125 0.182 0.069 0.000 0.000 0.000 0.000
##  [727] 0.000 0.000 0.000 0.333 0.333 0.333 0.500 0.000 0.500 0.000 0.000
##  [738] 0.000 0.000 0.500 0.000 0.000 0.000 0.500 0.000 0.000 0.000 0.000
##  [749] 0.000 1.000 0.000 0.000 0.000 0.000 0.000 0.000 1.000 0.000 0.497
##  [760] 0.434 0.480 0.463 0.457 0.414 0.452 0.465 0.392 0.423 0.442 0.453
##  [771] 0.439 0.419 0.445 0.436 0.379 0.482 0.451 0.369 0.387 0.443 0.428
##  [782] 0.425 0.410 0.406 0.396 0.335 0.379 0.376 0.376 0.346 0.357 0.380
##  [793] 0.370 0.366 0.386 0.341 0.344 0.385 0.360 0.358 0.319 0.389 0.441
##  [804] 0.369 0.376 0.415 0.329 0.337 0.313 0.301 0.385 0.276 0.312 0.315
##  [815] 0.337 0.274 0.278 1.000 1.000 1.000 0.727 0.714 0.800 0.500 0.500
##  [826] 0.600 0.500 0.447 0.375 0.404 0.438 0.396 0.411 0.429 0.440 0.469
##  [837] 0.385 0.536 0.402 0.398 0.420 0.343 0.364 0.408 0.388 0.500 0.388
##  [848] 0.333 0.250 0.328 0.273 0.362 0.326 0.306 0.350 0.333 0.339 0.344
##  [859] 0.388 0.400 0.455 0.455 0.333 0.250 0.250 0.342 0.300 0.310 0.275
##  [870] 0.333 0.364 0.274 0.253 0.313 0.270 0.333 0.333 0.333 0.306 0.253
##  [881] 0.326 0.231 0.250 0.379 0.357 0.250 0.293 0.316 0.257 0.313 0.353
##  [892] 0.305 0.217 0.333 0.333 0.250 0.364 0.300 0.245 0.242 0.115 0.176
##  [903] 0.267 0.000 0.400 0.000 0.250 0.167 0.167 0.200 0.200 0.000 0.000
##  [914] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
##  [925] 0.667 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
##  [936] 0.000 0.000 0.000 0.000 0.000 0.000 0.503 0.487 0.467 0.480 0.463
##  [947] 0.474 0.497 0.473 0.446 0.506 0.414 0.508 0.443 0.475 0.438 0.421
##  [958] 0.442 0.500 0.392 0.422 0.444 0.449 0.460 0.433 0.433 0.400 0.404
##  [969] 0.394 0.390 0.396 0.446 0.465 0.417 0.356 0.424 0.459 0.368 0.405
##  [980] 0.431 0.345 0.392 0.350 0.387 0.403 0.389 0.397 0.424 0.377 0.359
##  [991] 0.326 0.377 0.366 0.338 0.391 0.364 0.352 0.387 0.302 0.327 0.370
## [1002] 0.356 0.379 0.383 0.330 0.366 0.267 0.315 0.319 1.000 1.000 1.000
## [1013] 1.000 1.000 1.000 1.000 0.750 0.600 0.500 0.500 0.500 0.444 0.545
## [1024] 0.444 0.538 0.455 0.446 0.474 0.452 0.409 0.375 0.478 0.600 0.333
## [1035] 0.366 0.375 0.408 0.593 0.361 0.400 0.375 0.373 0.364 0.364 0.364
## [1046] 0.368 0.292 0.438 0.360 0.427 0.310 0.329 0.353 0.396 0.467 0.342
## [1057] 0.348 0.429 0.346 0.338 0.304 0.318 0.250 0.500 0.250 0.250 0.352
## [1068] 0.284 0.317 0.250 0.412 0.284 0.267 0.318 0.296 0.375 0.354 0.333
## [1079] 0.200 0.235 0.350 0.250 0.367 0.375 0.441 0.125 0.364 0.211 0.273
## [1090] 0.240 0.267 0.094 0.125 0.000 0.333 0.000 0.250 0.000 0.000 0.000
## [1101] 0.000 0.500 0.333 0.000 0.500 0.000 0.000 0.000 0.000 0.500 0.000
## [1112] 0.500 0.000 0.000 0.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000
## [1123] 0.000 0.000 1.000 0.000 1.000 0.000 0.000 0.000 1.000 0.511 0.445
## [1134] 0.459 0.481 0.455 0.449 0.490 0.488 0.436 0.425 0.452 0.430 0.426
## [1145] 0.428 0.433 0.454 0.444 0.446 0.413 0.465 0.435 0.397 0.480 0.394
## [1156] 0.423 0.425 0.447 0.430 0.440 0.379 0.391 0.377 0.385 0.395 0.399
## [1167] 0.376 0.346 0.456 0.365 0.415 0.443 0.392 0.438 0.394 0.390 0.357
## [1178] 0.382 0.363 0.379 0.371 0.344 0.323 0.388 0.371 0.357 0.345 0.330
## [1189] 0.356 0.314 0.279 0.372 0.298 0.304 0.320 1.000 1.000 0.667 0.667
## [1200] 0.625 0.500 0.750 0.500 0.500 0.429 0.429 0.514 0.418 0.406 0.474
## [1211] 0.444 0.415 0.420 0.423 0.409 0.379 0.333 0.429 0.333 0.667 0.451
## [1222] 0.402 0.352 0.365 0.481 0.388 0.407 0.393 0.367 0.298 0.378 0.308
## [1233] 0.339 0.348 0.333 0.311 0.308 0.402 0.392 0.328 0.342 0.327 0.370
## [1244] 0.390 0.354 0.286 0.391 0.333 0.333 0.250 0.250 0.296 0.304 0.278
## [1255] 0.350 0.271 0.286 0.375 0.300 0.297 0.310 0.231 0.360 0.258 0.208
## [1266] 0.235 0.250 0.192 0.286 0.262 0.333 0.308 0.333 0.206 0.267 0.226
## [1277] 0.111 0.154 0.071 0.333 0.111 0.053 0.000 0.111 0.000 0.000 0.000
## [1288] 0.000 0.000 0.500 0.000 0.000 0.000 0.500 0.000 0.000 0.000 0.000
## [1299] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [1310] 0.000 0.463 0.415 0.426 0.500 0.450 0.497 0.407 0.473 0.411 0.418
## [1321] 0.402 0.432 0.395 0.402 0.399 0.449 0.380 0.403 0.376 0.357 0.401
## [1332] 0.387 0.383 0.427 0.360 0.403 0.366 0.391 0.385 0.397 0.361 0.340
## [1343] 0.366 0.333 0.361 0.422 0.368 0.376 0.368 0.358 0.357 0.351 0.359
## [1354] 0.376 0.351 0.358 0.347 0.300 0.331 0.327 0.304 0.438 0.338 0.387
## [1365] 0.358 0.280 0.362 0.291 0.349 0.318 0.286 0.318 0.360 0.373 0.291
## [1376] 0.317 0.272 0.295 0.311 1.000 1.000 1.000 1.000 0.500 0.500 0.455
## [1387] 0.410 0.382 0.379 0.430 0.426 0.487 0.421 0.333 0.409 0.364 0.333
## [1398] 0.375 0.375 0.286 0.375 0.386 0.381 0.357 0.429 0.354 0.322 0.392
## [1409] 0.303 0.333 0.318 0.294 0.400 0.250 0.400 0.250 0.341 0.367 0.457
## [1420] 0.375 0.305 0.244 0.304 0.320 0.286 0.222 0.338 0.296 0.256 0.308
## [1431] 0.317 0.318 0.243 0.289 0.188 0.333 0.333 0.429 0.265 0.255 0.227
## [1442] 0.317 0.208 0.189 0.167 0.444 0.375 0.200 0.294 0.333 0.143 0.133
## [1453] 0.190 0.111 0.273 0.231 0.091 0.077 0.212 0.316 0.125 0.125 0.095
## [1464] 0.000 0.385 0.000 0.250 0.000 0.000 0.000 0.000 0.333 0.000 0.333
## [1475] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [1486] 1.000 0.485 0.396 0.403 0.427 0.466 0.402 0.399 0.412 0.415 0.399
## [1497] 0.361 0.390 0.412 0.390 0.395 0.353 0.380 0.457 0.371 0.407 0.362
## [1508] 0.412 0.374 0.351 0.379 0.376 0.351 0.359 0.338 0.402 0.388 0.399
## [1519] 0.387 0.347 0.328 0.385 0.353 0.374 0.315 0.370 0.384 0.350 0.353
## [1530] 0.336 0.328 0.324 0.367 0.316 0.338 0.349 0.379 0.318 0.306 0.394
## [1541] 0.368 0.331 0.368 0.401 0.362 0.309 0.324 0.353 0.295 0.259 0.389
## [1552] 0.243 1.000 0.571 0.571 0.480 0.484 0.450 0.435 0.429 0.438 0.370
## [1563] 0.394 0.333 0.500 0.379 0.485 0.417 0.394 0.368 0.442 0.316 0.427
## [1574] 0.379 0.348 0.385 0.429 0.333 0.278 0.340 0.352 0.291 0.333 0.333
## [1585] 0.250 0.250 0.378 0.269 0.375 0.318 0.375 0.375 0.280 0.329 0.286
## [1596] 0.326 0.457 0.267 0.267 0.372 0.296 0.440 0.385 0.375 0.273 0.333
## [1607] 0.333 0.333 0.248 0.313 0.350 0.212 0.240 0.277 0.271 0.270 0.200
## [1618] 0.313 0.262 0.320 0.167 0.143 0.176 0.364 0.167 0.200 0.100 0.182
## [1629] 0.154 0.241 0.000 0.000 0.286 0.000 0.000 0.250 0.000 0.000 0.000
## [1640] 0.000 0.000 0.250 0.250 0.000 0.000 0.000 0.333 0.000 0.000 0.000
## [1651] 0.000 0.000 0.500 0.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000
## [1662] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [1673] 0.000 0.525 0.446 0.475 0.432 0.413 0.446 0.427 0.409 0.378 0.404
## [1684] 0.420 0.388 0.418 0.493 0.389 0.371 0.362 0.348 0.448 0.347 0.350
## [1695] 0.347 0.417 0.376 0.382 0.361 0.395 0.331 0.379 0.327 0.360 0.392
## [1706] 0.347 0.359 0.367 0.331 0.377 0.351 0.342 0.369 0.310 0.346 0.352
## [1717] 0.303 0.293 0.327 0.358 0.345 0.391 0.292 0.330 0.303 0.321 0.266
## [1728] 0.248 0.248 1.000 0.500 0.421 0.366 0.333 0.333 0.333 0.333 0.500
## [1739] 0.431 0.421 0.345 0.363 0.360 0.400 0.382 0.342 0.356 0.304 0.394
## [1750] 0.377 0.389 0.304 0.339 0.347 0.313 0.345 0.320 0.319 0.287 0.349
## [1761] 0.262 0.289 0.297 0.329 0.272 0.270 0.287 0.286 0.412 0.333 0.289
## [1772] 0.368 0.305 0.382 0.242 0.353 0.260 0.310 0.300 0.250 0.200 0.265
## [1783] 0.272 0.261 0.167 0.375 0.182 0.125 0.263 0.222 0.219 0.158 0.111
## [1794] 0.111 0.167 0.170 0.130 0.135 0.143 0.071 0.143 0.050 0.125 0.400
## [1805] 0.000 0.000 0.000 0.000 0.000 0.000 0.250 0.000 0.000 0.000 0.000
## [1816] 0.000 0.500 0.000 0.000 0.000 0.000 0.000 0.500 0.000 0.000 0.000
## [1827] 0.000 1.000 0.000 0.000 0.000 0.000 0.000 0.469 0.401 0.398 0.405
## [1838] 0.401 0.414 0.405 0.400 0.421 0.443 0.422 0.411 0.376 0.394 0.359
## [1849] 0.371 0.406 0.408 0.407 0.380 0.431 0.367 0.416 0.358 0.386 0.366
## [1860] 0.420 0.370 0.392 0.439 0.362 0.330 0.367 0.385 0.350 0.289 0.398
## [1871] 0.417 0.345 0.358 0.345 0.357 0.374 0.341 0.341 0.357 0.353 0.355
## [1882] 0.399 0.315 0.385 0.299 0.360 0.338 0.302 0.338 0.289 0.246 0.375
## [1893] 0.429 0.412 0.390 0.407 0.391 0.333 0.333 0.441 0.362 0.390 0.416
## [1904] 0.357 0.349 0.333 0.393 0.313 0.321 0.343 0.350 0.313 0.429 0.328
## [1915] 0.388 0.313 0.364 0.300 0.393 0.310 0.324 0.357 0.273 0.348 0.250
## [1926] 0.333 0.320 0.364 0.233 0.363 0.281 0.289 0.269 0.207 0.200 0.333
## [1937] 0.467 0.333 0.283 0.262 0.267 0.264 0.290 0.269 0.182 0.167 0.299
## [1948] 0.245 0.200 0.389 0.180 0.167 0.400 0.174 0.125 0.222 0.303 0.209
## [1959] 0.250 0.120 0.186 0.400 0.143 0.000 0.286 0.429 0.250 0.250 0.000
## [1970] 0.500 0.000 0.000 0.000 0.500 0.000 0.000 0.000 0.000 0.000 1.000
## [1981] 0.000 0.000 0.000 1.000 0.491 0.459 0.405 0.486 0.468 0.411 0.498
## [1992] 0.472 0.415 0.414 0.447 0.454 0.459 0.456 0.400 0.409 0.424 0.417
## [2003] 0.458 0.401 0.371 0.406 0.382 0.396 0.442 0.429 0.396 0.421 0.451
## [2014] 0.360 0.416 0.422 0.411 0.413 0.397 0.348 0.350 0.380 0.363 0.344
## [2025] 0.360 0.315 0.402 0.387 0.404 0.366 0.384 0.350 0.350 0.301 0.375
## [2036] 0.306 0.365 0.327 0.317 0.292 0.328 0.345 0.305 0.283 0.286 0.340
## [2047] 0.287 0.500 0.455 0.471 0.400 0.452 0.318 0.429 0.333 0.400 0.500
## [2058] 0.376 0.410 0.360 0.313 0.361 0.500 0.407 0.351 0.365 0.286 0.323
## [2069] 0.333 0.395 0.353 0.345 0.261 0.326 0.355 0.329 0.357 0.380 0.417
## [2080] 0.375 0.321 0.407 0.273 0.300 0.319 0.328 0.222 0.375 0.300 0.279
## [2091] 0.309 0.326 0.220 0.347 0.200 0.333 0.300 0.288 0.300 0.231 0.167
## [2102] 0.286 0.257 0.238 0.154 0.261 0.143 0.143 0.125 0.200 0.222 0.162
## [2113] 0.238 0.111 0.154 0.286 0.167 0.200 0.250 0.261 0.200 0.333 0.600
## [2124] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [2135] 0.000 0.000 0.000 0.000 1.000 0.000 0.000 1.000 0.462 0.478 0.403
## [2146] 0.422 0.500 0.322 0.455 0.408 0.415 0.353 0.363 0.317 0.340 0.366
## [2157] 0.211 0.125 0.300 0.000 0.500 0.000 0.000 0.395 0.388 0.456 0.390
## [2168] 0.383 0.406 0.401 0.439 0.375 0.410 0.400 0.336 0.276 0.000 0.000
## [2179] 1.000 0.500 0.488 0.457 0.438 0.411 0.438 0.370 0.401 0.350 0.362
## [2190] 0.452 0.308 0.250 0.292 0.333 0.250 0.000 0.000 0.000 0.000 1.000
## [2201] 0.383 0.393 0.426 0.391 0.377 0.325 0.273 0.331 0.295 0.292 0.229
## [2212] 0.000 0.000 0.000 1.000 0.000 0.000 0.430 0.429 0.440 0.474 0.387
## [2223] 0.452 0.407 0.360 0.330 0.375 0.303 0.315 0.500 0.214 0.182 0.000
## [2234] 0.200 0.200 0.000 0.000 0.000 0.500 0.667 0.472 0.411 0.410 0.333
## [2245] 0.333 0.375 0.440 0.389 0.364 0.379 0.324 0.311 0.330 0.288 0.200
## [2256] 0.293 0.231 0.304 0.222 0.083 0.000 0.000 0.000 0.000 0.468 0.403
## [2267] 0.397 0.357 0.391 0.381 0.391 0.369 0.328 0.350 0.400 0.429 0.345
## [2278] 0.000 0.000 0.333 0.000 0.000 1.000 0.476 0.479 0.492 0.423 0.411
## [2289] 0.427 0.377 0.477 0.333 0.366 0.377 0.333 0.133 0.273 0.200 0.000
## [2300] 0.000 0.000 0.000 0.461 0.437 0.464 0.374 0.379 0.391 0.349 0.341
## [2311] 0.385 0.360 0.250 0.250 0.357 0.167 0.000 0.000 0.000 0.000 0.000
## [2322] 0.000 0.000 0.473 0.362 0.384 0.432 0.339 0.384 0.281 0.348 0.364
## [2333] 0.368 0.295 0.375 0.270 0.235 0.250 0.143 0.000 0.000 1.000 0.000
## [2344] 0.543 0.427 0.442 0.389 0.495 0.397 0.424 0.316 0.416 0.429 0.400
## [2355] 0.292 0.300 0.000 0.000 0.442 0.526 0.407 0.418 0.408 0.413 0.361
## [2366] 0.342 0.314 0.400 0.333 0.250 0.400 0.143 0.167 0.000 0.000 0.000
## [2377] 0.000 0.000 0.000 0.435 0.358 0.412 0.406 0.325 0.341 0.296 0.529
## [2388] 0.293 0.247 0.290 0.333 0.000 0.000 0.000 0.000 0.474 0.412 0.389
## [2399] 0.362 0.266 0.408 0.429 0.333 0.400 0.359 0.415 0.314 0.250 0.222
## [2410] 0.290 0.188 0.438 0.300 0.310 0.213 0.231 0.238 0.000 0.000 0.000
## [2421] 0.000 1.000 0.424 0.383 0.312 0.362 0.363 0.500 0.473 0.336 0.381
## [2432] 0.323 0.286 0.313 0.353 0.271 0.328 0.000 0.000 0.000 0.000 0.511
## [2443] 0.488 0.417 0.373 0.394 0.306 0.409 0.371 0.382 0.365 0.412 0.292
## [2454] 0.330 0.167 0.250 0.000 0.000 0.496 0.478 0.534 0.415 0.388 0.386
## [2465] 0.354 0.500 0.714 0.500 0.800 0.432 0.426 0.402 0.297 0.219 0.462
## [2476] 0.000 0.000 0.000 0.476 0.480 0.388 0.401 0.326 0.292 0.500 0.484
## [2487] 0.427 0.447 0.365 0.250 0.353 0.352 0.463 0.200 0.375 0.167 0.357
## [2498] 0.207 0.267 0.000 0.470 0.451 0.462 0.437 0.392 0.419 0.404 0.393
## [2509] 0.444 0.420 0.435 0.419 0.430 0.428 0.404 0.406 0.411 0.415 0.403
## [2520] 0.353 0.392 0.378 0.386 0.401 0.410 0.413 0.349 0.397 0.399 0.326
## [2531] 0.401 0.368 0.387 0.370 0.384 0.352 0.359 0.337 0.357 0.358 0.398
## [2542] 0.371 0.339 0.438 0.365 0.348 0.386 0.401 0.318 0.335 0.380 0.333
## [2553] 0.351 0.338 0.316 0.351 0.362 0.348 0.308 0.318 0.295 0.309 0.279
## [2564] 0.333 0.303 0.327 0.292 0.274 0.269 0.328 0.280 0.312 0.218 1.000
## [2575] 0.667 0.667 0.478 0.467 0.429 0.500 0.451 0.444 0.424 0.385 0.364
## [2586] 0.333 0.345 0.349 0.371 0.398 0.267 0.286 0.337 0.345 0.382 0.300
## [2597] 0.333 0.330 0.313 0.337 0.304 0.375 0.250 0.250 0.400 0.400 0.288
## [2608] 0.267 0.293 0.412 0.375 0.313 0.321 0.292 0.292 0.318 0.364 0.324
## [2619] 0.242 0.256 0.250 0.292 0.269 0.317 0.200 0.429 0.333 0.280 0.316
## [2630] 0.381 0.354 0.256 0.241 0.208 0.286 0.315 0.284 0.167 0.250 0.322
## [2641] 0.214 0.243 0.205 0.258 0.143 0.161 0.460 0.200 0.152 0.267 0.133
## [2652] 0.077 0.000 0.000 0.000 0.000 0.250 0.000 0.000 0.000 0.000 0.333
## [2663] 0.333 0.000 0.000 0.000 0.000 0.000 0.000 0.000 1.000 1.000 0.000
## [2674] 0.000 1.000 0.000 0.000 0.470 0.436 0.470 0.417 0.453 0.415 0.402
## [2685] 0.418 0.441 0.422 0.420 0.388 0.444 0.420 0.430 0.405 0.379 0.381
## [2696] 0.397 0.377 0.373 0.423 0.373 0.384 0.409 0.393 0.387 0.346 0.349
## [2707] 0.404 0.408 0.330 0.331 0.404 0.340 0.352 0.385 0.376 0.362 0.364
## [2718] 0.345 0.379 0.366 0.333 0.333 0.347 0.342 0.348 0.331 0.314 0.350
## [2729] 0.331 0.350 0.337 0.340 0.317 0.333 0.227 0.304 1.000 0.556 0.800
## [2740] 0.500 0.500 0.565 0.451 0.412 0.431 0.468 0.440 0.469 0.418 0.417
## [2751] 0.434 0.400 0.474 0.500 0.444 0.333 0.333 0.377 0.314 0.414 0.422
## [2762] 0.444 0.322 0.466 0.278 0.318 0.314 0.360 0.333 0.345 0.353 0.298
## [2773] 0.363 0.378 0.333 0.313 0.424 0.500 0.250 0.359 0.306 0.342 0.310
## [2784] 0.289 0.370 0.238 0.381 0.333 0.262 0.444 0.355 0.267 0.253 0.278
## [2795] 0.329 0.267 0.281 0.278 0.329 0.297 0.385 0.316 0.283 0.276 0.250
## [2806] 0.353 0.287 0.257 0.263 0.296 0.263 0.316 0.308 0.234 0.357 0.308
## [2817] 0.182 0.333 0.286 0.318 0.286 0.375 0.167 0.167 0.238 0.329 0.188
## [2828] 0.417 0.333 0.250 0.231 0.125 0.333 0.167 0.000 0.100 0.143 0.250
## [2839] 0.429 0.200 0.000 0.000 0.400 0.000 0.000 0.000 0.000 0.333 0.000
## [2850] 0.333 0.500 0.000 0.000 0.000 0.000 0.000 0.000 0.000 1.000 0.000
## [2861] 0.000 0.000 0.000 0.000 1.000 0.000 0.429 0.382 0.391 0.465 0.368
## [2872] 0.370 0.381 1.000 0.500 0.469 0.411 0.362 0.367 0.406 0.364 0.256
## [2883] 0.357 0.167 0.000 0.000 0.000 0.470 0.443 0.365 0.374 0.319 0.310
## [2894] 0.299 0.306 0.381 0.375 0.325 0.308 0.304 0.383 0.133 0.000 0.333
## [2905] 0.000 0.510 0.375 0.421 0.429 0.378 0.336 0.372 0.327 0.311 0.364
## [2916] 0.312 0.313 0.357 0.269 0.000 0.000 0.000 0.000 0.500 0.273 0.182
## [2927] 0.100 0.167 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.500
## [2938] 0.462 0.353 0.390 0.333 0.405 0.380 0.380 0.433 0.319 0.310 0.328
## [2949] 0.291 0.000 0.400 0.150 0.000 0.429 0.000 0.452 0.432 0.414 0.383
## [2960] 0.309 0.324 0.302 1.000 0.571 0.500 0.750 0.419 0.338 0.373 0.293
## [2971] 0.449 0.364 0.365 0.125 0.000 0.500 0.439 0.407 0.388 0.361 0.351
## [2982] 0.364 0.348 0.359 0.321 0.294 0.377 0.289 0.250 0.500 0.333 0.000
## [2993] 0.462 0.406 0.325 0.353 0.311 0.353 0.323 0.403 0.241 0.331 0.325
## [3004] 0.257 0.333 0.246 0.245 0.286 0.100 0.222 0.000 0.000 0.000 0.000
## [3015] 0.000 0.458 0.431 0.412 0.330 0.359 0.374 0.412 0.341 0.363 0.303
## [3026] 0.342 0.316 0.300 0.300 0.211 0.182 0.000 0.394 0.371 0.375 0.342
## [3037] 0.374 0.338 0.308 0.276 0.353 0.342 0.200 0.231 0.192 0.000 0.400
## [3048] 0.000 1.000
```

```
## Warning: NAs introduced by coercion
```

```
##    [1] 0.794 0.790 0.714 0.645 0.874 0.731 0.683 0.496 0.574 0.519 0.604
##   [12] 0.786 0.497 0.618 0.575 0.661 0.473 0.667 0.600 0.659 0.439 0.504
##   [23] 0.377 0.603 0.568 0.500 0.454 0.527 0.465 0.389 0.475 0.366 0.460
##   [34] 0.516 0.479 0.355 0.372 0.423 0.495 0.401 0.411 0.555 0.431 0.365
##   [45] 0.377 0.471 0.284 0.434 0.352 0.353 0.358 0.313 0.254 0.303 0.333
##   [56] 0.278 2.000 1.000 1.000 0.667 0.750 0.500 0.500 0.688 0.577 0.597
##   [67] 0.600 0.562 0.600 0.433 0.439 0.440 0.487 0.500 0.478 0.533 0.575
##   [78] 0.333 0.324 0.473 0.571 0.415 0.477 0.406 0.313 0.365 0.464 0.400
##   [89] 0.337 0.409 0.325 0.400 0.300 0.294 0.394 0.385 0.404 0.348 0.364
##  [100] 0.295 0.542 0.382 0.312 0.469 0.265 0.263 0.316 0.313 0.397 0.288
##  [111] 0.296 0.346 0.342 0.288 0.364 0.464 0.250 0.250 0.250 0.250 0.301
##  [122] 0.400 0.309 0.294 0.294 0.298 0.367 0.385 0.340 0.250 0.418 0.261
##  [133] 0.214 0.214 0.286 0.377 0.241 0.282 0.288 0.200 0.254 0.190 0.281
##  [144] 0.259 0.256 0.250 0.179 0.333 0.188 0.185 0.143 0.286 0.200 0.128
##  [155] 0.125 0.294 0.105 0.105 0.091 0.056 0.036 0.000 0.000 0.000 0.000
##  [166] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
##  [177] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
##  [188] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
##  [199] 0.000 0.000 1.000 2.000 0.750 0.667 0.750 1.500 1.000 0.533 0.762
##  [210] 0.571 0.567 0.545 0.454 0.606 0.600 0.480 0.590 0.676 0.838 0.556
##  [221] 0.437 0.615 0.623 0.532 0.647 0.448 0.612 0.573 0.551 0.573 0.368
##  [232] 0.477 0.364 0.594 0.603 0.389 0.487 0.473 0.463 0.481 0.464 0.439
##  [243] 0.583 0.465 0.625 0.674 0.445 0.465 0.412 0.333 0.556 0.667 0.333
##  [254] 0.497 0.455 0.469 0.462 0.374 0.423 0.543 0.424 0.516 0.535 0.345
##  [265] 0.460 0.523 0.385 0.429 0.338 0.629 0.300 0.511 0.416 0.492 0.516
##  [276] 0.364 0.294 0.429 0.369 0.460 0.391 0.316 0.327 0.391 0.333 0.369
##  [287] 0.448 0.386 0.281 0.337 0.445 0.403 0.325 0.394 0.429 0.273 0.273
##  [298] 0.361 0.432 0.324 0.365 0.387 0.427 0.351 0.416 0.333 0.330 0.314
##  [309] 0.360 0.295 0.405 0.295 0.326 0.409 0.292 0.333 0.250 0.463 0.290
##  [320] 0.240 0.429 0.235 0.231 0.231 0.314 0.323 0.367 0.222 0.222 0.214
##  [331] 0.286 0.303 0.273 0.275 0.242 0.242 0.239 0.235 0.256 0.275 0.200
##  [342] 0.337 0.194 0.296 0.182 0.273 0.200 0.194 0.194 0.167 0.189 0.220
##  [353] 0.211 0.250 0.125 0.125 0.091 0.000 0.000 0.000 0.000 0.000 0.000
##  [364] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
##  [375] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
##  [386] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 1.500
##  [397] 1.000 1.000 1.000 1.000 1.000 0.667 0.500 0.667 0.500 0.500 0.500
##  [408] 0.500 0.650 0.571 0.888 0.686 0.675 0.697 0.664 0.400 0.407 0.686
##  [419] 0.585 0.658 0.626 0.732 0.524 0.439 0.612 0.675 0.543 0.604 0.500
##  [430] 0.442 0.551 0.412 0.424 0.508 0.507 0.422 0.522 0.455 0.407 0.429
##  [441] 0.386 0.423 0.407 0.575 0.582 0.397 0.465 0.507 0.327 0.471 0.406
##  [452] 0.524 0.354 0.423 0.364 0.426 0.571 0.384 0.424 0.534 0.366 0.382
##  [463] 0.397 0.364 0.433 0.374 0.417 0.362 0.392 0.421 0.407 0.342 0.378
##  [474] 0.329 0.529 0.477 0.388 0.440 0.472 0.455 0.297 0.314 0.445 0.286
##  [485] 0.322 0.344 0.476 0.354 0.309 0.297 0.346 0.275 0.350 0.311 0.317
##  [496] 0.272 0.311 0.284 0.268 0.290 0.324 0.571 0.307 0.235 0.235 0.406
##  [507] 0.267 0.346 0.272 0.333 0.278 0.444 0.333 0.286 0.364 0.273 0.273
##  [518] 0.200 0.600 0.200 0.200 0.200 0.226 0.269 0.250 0.273 0.240 0.255
##  [529] 0.250 0.308 0.154 0.159 0.138 0.281 0.118 0.111 0.222 0.100 0.115
##  [540] 0.050 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
##  [551] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
##  [562] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
##  [573] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
##  [584] 0.578 0.491 0.605 0.631 0.455 0.512 0.610 0.626 0.564 0.632 0.521
##  [595] 0.462 0.456 0.441 0.519 0.450 0.480 0.442 0.495 0.471 0.439 0.352
##  [606] 0.500 0.466 0.385 0.384 0.519 0.461 0.432 0.470 0.364 0.450 0.376
##  [617] 0.482 0.411 0.474 0.489 0.381 0.370 0.432 0.361 0.333 0.310 0.391
##  [628] 0.367 0.355 0.333 0.333 0.349 0.263 0.263 0.290 0.358 0.289 0.287
##  [639] 0.283 0.270 0.333 0.275 0.272 0.242 0.371 1.000 2.000 1.000 1.000
##  [650] 0.500 0.750 0.500 0.500 0.516 0.455 0.560 0.452 0.500 0.459 0.429
##  [661] 0.471 0.483 0.431 0.381 0.406 0.318 0.330 0.352 0.353 0.351 0.560
##  [672] 0.323 0.389 0.293 0.300 0.333 0.273 0.288 0.363 0.298 0.263 0.298
##  [683] 0.323 0.257 0.429 0.322 0.250 0.500 0.250 0.250 0.258 0.267 0.289
##  [694] 0.231 0.260 0.435 0.241 0.250 0.444 0.333 0.222 0.293 0.261 0.235
##  [705] 0.214 0.263 0.250 0.200 0.194 0.205 0.189 0.256 0.229 0.167 0.344
##  [716] 0.232 0.130 0.188 0.125 0.125 0.100 0.036 0.000 0.000 0.000 0.000
##  [727] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
##  [738] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
##  [749] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.653
##  [760] 0.514 0.659 0.652 0.535 0.496 0.496 0.530 0.478 0.517 0.454 0.414
##  [771] 0.451 0.532 0.400 0.423 0.538 0.468 0.563 0.507 0.471 0.412 0.373
##  [782] 0.490 0.413 0.406 0.504 0.434 0.440 0.389 0.678 0.348 0.402 0.430
##  [793] 0.469 0.414 0.345 0.370 0.303 0.485 0.378 0.420 0.341 0.372 0.352
##  [804] 0.385 0.348 0.326 0.396 0.405 0.378 0.301 0.310 0.383 0.320 0.288
##  [815] 0.355 0.270 0.292 1.000 1.000 1.000 1.000 0.750 0.500 0.500 0.500
##  [826] 0.571 0.500 0.553 0.641 0.463 0.459 0.385 0.444 0.583 0.329 0.320
##  [837] 0.378 0.342 0.380 0.426 0.446 0.350 0.425 0.500 0.341 0.714 0.379
##  [848] 0.273 0.364 0.441 0.286 0.268 0.286 0.348 0.365 0.352 0.309 0.288
##  [859] 0.250 0.333 0.250 0.375 0.375 0.250 0.750 0.333 0.297 0.289 0.318
##  [870] 0.231 0.222 0.221 0.351 0.214 0.246 0.200 0.200 0.200 0.226 0.274
##  [881] 0.241 0.216 0.323 0.182 0.182 0.182 0.200 0.207 0.194 0.231 0.308
##  [892] 0.194 0.145 0.143 0.143 0.130 0.125 0.125 0.143 0.111 0.200 0.067
##  [903] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
##  [914] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
##  [925] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
##  [936] 0.000 0.000 0.000 0.000 0.000 0.000 0.736 0.588 0.605 0.551 0.604
##  [947] 0.593 0.599 0.655 0.500 0.559 0.513 0.462 0.478 0.556 0.566 0.493
##  [958] 0.679 0.421 0.576 0.545 0.427 0.559 0.442 0.449 0.503 0.439 0.531
##  [969] 0.487 0.437 0.579 0.516 0.472 0.514 0.469 0.518 0.526 0.447 0.445
##  [980] 0.436 0.489 0.389 0.432 0.463 0.376 0.479 0.459 0.324 0.366 0.412
##  [991] 0.427 0.486 0.423 0.438 0.305 0.337 0.391 0.381 0.433 0.366 0.322
## [1002] 0.341 0.445 0.362 0.333 0.314 0.268 0.241 0.258 2.000 1.000 1.000
## [1013] 1.000 1.000 1.000 1.000 0.667 0.600 1.000 0.500 0.500 0.444 0.600
## [1024] 0.600 0.600 0.700 0.420 0.404 0.480 0.583 0.367 0.333 0.333 0.333
## [1035] 0.422 0.682 0.366 0.313 0.446 0.308 0.422 0.433 0.375 0.400 0.800
## [1046] 0.373 0.417 0.368 0.377 0.310 0.402 0.440 0.373 0.316 0.456 0.306
## [1057] 0.415 0.342 0.348 0.318 0.490 0.250 0.500 0.250 0.250 0.250 0.311
## [1068] 0.379 0.324 0.431 0.385 0.290 0.214 0.368 0.333 0.250 0.299 0.250
## [1079] 0.200 0.375 0.188 0.455 0.174 0.167 0.182 0.125 0.125 0.176 0.111
## [1090] 0.143 0.083 0.033 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [1101] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [1112] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [1123] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.773 0.624
## [1134] 0.547 0.771 0.605 0.639 0.719 0.488 0.682 0.539 0.431 0.517 0.526
## [1145] 0.645 0.437 0.698 0.455 0.660 0.579 0.397 0.597 0.474 0.441 0.466
## [1156] 0.515 0.410 0.413 0.469 0.639 0.428 0.472 0.528 0.467 0.401 0.461
## [1167] 0.496 0.375 0.411 0.368 0.495 0.489 0.434 0.329 0.409 0.507 0.409
## [1178] 0.392 0.385 0.385 0.324 0.514 0.301 0.306 0.343 0.323 0.329 0.378
## [1189] 0.312 0.341 0.293 0.326 0.290 0.242 0.198 1.000 1.000 0.667 0.667
## [1200] 0.500 0.500 0.500 0.500 0.500 0.600 0.385 0.586 0.667 0.459 0.563
## [1211] 0.375 0.400 0.507 0.435 0.530 0.407 0.500 0.667 0.333 0.333 0.373
## [1222] 0.373 0.480 0.382 0.410 0.492 0.433 0.489 0.333 0.418 0.312 0.327
## [1233] 0.500 0.355 0.364 0.424 0.351 0.333 0.390 0.283 0.382 0.413 0.261
## [1244] 0.303 0.427 0.400 0.250 0.281 0.250 0.250 0.250 0.240 0.333 0.324
## [1255] 0.353 0.247 0.385 0.231 0.444 0.327 0.364 0.240 0.250 0.246 0.298
## [1266] 0.188 0.242 0.208 0.250 0.162 0.214 0.143 0.143 0.172 0.120 0.111
## [1277] 0.222 0.083 0.071 0.133 0.067 0.000 0.000 0.000 0.000 0.000 0.000
## [1288] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [1299] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [1310] 0.000 0.527 0.531 0.484 0.514 0.503 0.680 0.432 0.484 0.466 0.579
## [1321] 0.402 0.398 0.390 0.426 0.386 0.477 0.448 0.364 0.451 0.365 0.439
## [1332] 0.440 0.622 0.371 0.373 0.439 0.450 0.424 0.547 0.496 0.345 0.430
## [1343] 0.361 0.387 0.355 0.376 0.337 0.364 0.346 0.553 0.480 0.365 0.297
## [1354] 0.478 0.381 0.427 0.363 0.307 0.308 0.400 0.306 0.303 0.278 0.290
## [1365] 0.275 0.324 0.315 0.371 0.350 0.299 0.313 0.281 0.243 0.236 0.256
## [1376] 0.288 0.232 0.246 0.189 2.000 1.000 1.000 1.000 0.500 0.500 0.400
## [1387] 0.648 0.424 0.429 0.434 0.420 0.390 0.397 0.333 0.368 0.350 0.300
## [1398] 0.357 0.393 0.286 0.429 0.353 0.333 0.274 0.273 0.296 0.338 0.286
## [1409] 0.446 0.250 0.350 0.375 0.250 0.250 0.500 0.500 0.297 0.260 0.240
## [1420] 0.237 0.269 0.250 0.250 0.254 0.333 0.222 0.254 0.304 0.297 0.357
## [1431] 0.212 0.211 0.235 0.441 0.200 0.400 0.300 0.200 0.246 0.209 0.233
## [1442] 0.180 0.174 0.171 0.167 0.167 0.167 0.152 0.143 0.143 0.143 0.133
## [1453] 0.111 0.111 0.111 0.091 0.091 0.077 0.071 0.071 0.133 0.067 0.000
## [1464] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [1475] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [1486] 0.000 0.431 0.487 0.439 0.545 0.602 0.479 0.430 0.619 0.430 0.437
## [1497] 0.409 0.390 0.424 0.451 0.518 0.374 0.392 0.372 0.412 0.367 0.374
## [1508] 0.443 0.379 0.362 0.424 0.422 0.423 0.396 0.338 0.459 0.406 0.515
## [1519] 0.358 0.333 0.383 0.348 0.453 0.453 0.343 0.375 0.302 0.320 0.362
## [1530] 0.312 0.320 0.295 0.311 0.317 0.321 0.326 0.303 0.329 0.328 0.313
## [1541] 0.278 0.289 0.304 0.270 0.313 0.357 0.300 0.232 0.227 0.261 0.261
## [1552] 0.232 1.000 0.714 0.545 0.550 0.500 0.500 0.436 0.421 0.463 0.400
## [1563] 0.433 0.333 0.667 0.393 0.365 0.325 0.402 0.508 0.377 0.377 0.310
## [1574] 0.280 0.325 0.341 0.455 0.263 0.371 0.349 0.304 0.288 0.400 0.313
## [1585] 0.250 0.500 0.316 0.400 0.280 0.273 0.385 0.308 0.329 0.273 0.222
## [1596] 0.247 0.239 0.250 0.214 0.236 0.292 0.237 0.200 0.240 0.200 0.300
## [1607] 0.200 0.400 0.237 0.208 0.250 0.250 0.239 0.195 0.190 0.156 0.154
## [1618] 0.154 0.194 0.150 0.171 0.143 0.188 0.125 0.118 0.111 0.100 0.100
## [1629] 0.087 0.083 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [1640] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [1651] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [1662] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [1673] 0.000 0.550 0.512 0.487 0.550 0.401 0.625 0.448 0.459 0.424 0.614
## [1684] 0.369 0.382 0.377 0.353 0.468 0.397 0.408 0.374 0.471 0.403 0.380
## [1695] 0.352 0.295 0.311 0.528 0.333 0.314 0.431 0.343 0.437 0.371 0.370
## [1706] 0.425 0.363 0.360 0.386 0.390 0.303 0.317 0.277 0.336 0.291 0.366
## [1717] 0.299 0.259 0.301 0.281 0.268 0.284 0.264 0.294 0.306 0.248 0.224
## [1728] 0.283 0.179 1.000 0.500 0.558 0.421 0.389 0.333 0.333 0.333 0.333
## [1739] 0.426 0.500 0.385 0.397 0.537 0.328 0.298 0.290 0.300 0.409 0.339
## [1750] 0.333 0.267 0.388 0.291 0.299 0.341 0.375 0.326 0.295 0.308 0.297
## [1761] 0.293 0.310 0.294 0.235 0.299 0.267 0.279 0.256 0.231 0.308 0.286
## [1772] 0.323 0.266 0.241 0.250 0.214 0.284 0.200 0.200 0.300 0.200 0.290
## [1783] 0.247 0.238 0.250 0.167 0.200 0.150 0.125 0.250 0.160 0.111 0.111
## [1794] 0.111 0.179 0.095 0.093 0.118 0.231 0.071 0.105 0.100 0.000 0.000
## [1805] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [1816] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [1827] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.567 0.538 0.484 0.500
## [1838] 0.559 0.466 0.510 0.602 0.602 0.626 0.556 0.485 0.519 0.506 0.540
## [1849] 0.407 0.452 0.403 0.454 0.466 0.488 0.441 0.434 0.432 0.408 0.356
## [1860] 0.404 0.461 0.556 0.401 0.478 0.311 0.376 0.350 0.444 0.369 0.368
## [1871] 0.345 0.347 0.342 0.355 0.352 0.286 0.336 0.323 0.339 0.311 0.372
## [1882] 0.397 0.296 0.410 0.379 0.280 0.291 0.269 0.269 0.276 0.176 0.571
## [1893] 0.429 0.500 0.493 0.437 0.476 0.333 0.333 0.321 0.520 0.403 0.365
## [1904] 0.308 0.300 0.512 0.357 0.286 0.321 0.535 0.333 0.386 0.273 0.288
## [1915] 0.323 0.333 0.426 0.351 0.261 0.259 0.317 0.250 0.250 0.400 0.250
## [1926] 0.311 0.311 0.265 0.300 0.328 0.250 0.212 0.208 0.241 0.267 0.200
## [1937] 0.200 0.200 0.213 0.243 0.288 0.250 0.222 0.267 0.273 0.333 0.266
## [1948] 0.279 0.184 0.154 0.170 0.143 0.286 0.136 0.125 0.125 0.115 0.135
## [1959] 0.100 0.125 0.105 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [1970] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [1981] 0.000 0.000 0.000 0.000 0.546 0.592 0.438 0.623 0.651 0.430 0.675
## [1992] 0.559 0.507 0.509 0.687 0.629 0.500 0.656 0.416 0.438 0.400 0.417
## [2003] 0.500 0.417 0.420 0.514 0.496 0.362 0.486 0.384 0.455 0.523 0.452
## [2014] 0.458 0.522 0.470 0.638 0.430 0.510 0.339 0.503 0.441 0.391 0.440
## [2025] 0.309 0.475 0.397 0.328 0.321 0.469 0.388 0.356 0.388 0.357 0.293
## [2036] 0.315 0.281 0.427 0.424 0.320 0.446 0.286 0.371 0.278 0.301 0.289
## [2047] 0.272 0.500 0.636 0.467 0.400 0.462 0.432 0.333 0.333 0.556 0.333
## [2058] 0.533 0.618 0.494 0.379 0.387 0.425 0.377 0.324 0.355 0.286 0.317
## [2069] 0.333 0.414 0.283 0.374 0.348 0.273 0.296 0.324 0.292 0.270 0.243
## [2080] 0.261 0.261 0.262 0.333 0.284 0.300 0.259 0.278 0.278 0.556 0.255
## [2091] 0.229 0.231 0.275 0.325 0.200 0.182 0.176 0.246 0.238 0.208 0.167
## [2102] 0.167 0.161 0.158 0.154 0.150 0.143 0.143 0.250 0.125 0.125 0.114
## [2113] 0.167 0.333 0.108 0.182 0.273 0.077 0.063 0.059 0.000 0.000 0.000
## [2124] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [2135] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 1.000 0.417 0.555 0.401
## [2146] 0.419 0.333 0.333 0.496 0.504 0.420 0.324 0.340 0.371 0.378 0.242
## [2157] 0.316 0.250 0.125 0.000 0.000 0.000 0.000 0.497 0.549 0.764 0.454
## [2168] 0.347 0.423 0.493 0.447 0.286 0.365 0.365 0.373 0.160 0.000 0.000
## [2179] 0.000 1.000 0.743 0.644 0.385 0.588 0.504 0.414 0.586 0.471 0.508
## [2190] 0.366 0.333 0.250 0.307 0.271 0.316 0.000 0.000 0.000 0.000 1.000
## [2201] 0.403 0.500 0.435 0.517 0.388 0.353 0.333 0.339 0.339 0.273 0.348
## [2212] 0.000 0.000 0.000 0.000 0.000 0.000 0.537 0.368 0.426 0.439 0.539
## [2223] 0.348 0.423 0.345 0.359 0.396 0.395 0.304 0.182 0.154 0.100 0.000
## [2234] 0.000 0.000 0.000 0.000 0.000 0.500 0.667 0.561 0.612 0.352 0.333
## [2245] 0.333 0.439 0.457 0.375 0.500 0.354 0.386 0.463 0.294 0.298 0.200
## [2256] 0.314 0.167 0.158 0.149 0.333 0.000 0.000 0.000 0.000 0.669 0.374
## [2267] 0.571 0.379 0.411 0.427 0.625 0.316 0.402 0.326 0.250 0.200 0.230
## [2278] 0.000 0.000 0.000 0.000 0.000 1.000 0.707 0.470 0.716 0.464 0.599
## [2289] 0.532 0.525 0.540 0.333 0.433 0.524 0.400 0.200 0.294 0.000 0.000
## [2300] 0.000 0.000 0.000 0.653 0.617 0.482 0.471 0.410 0.398 0.552 0.373
## [2311] 0.305 0.296 0.250 0.263 0.182 0.091 0.000 0.000 0.000 0.000 0.000
## [2322] 0.000 0.000 0.484 0.385 0.505 0.538 0.350 0.311 0.364 0.442 0.400
## [2333] 0.333 0.339 0.231 0.209 0.133 0.100 0.077 0.000 0.000 0.000 0.000
## [2344] 0.785 0.531 0.352 0.486 0.496 0.390 0.415 0.221 0.372 0.333 0.224
## [2355] 0.232 0.125 0.000 0.000 0.559 0.603 0.478 0.547 0.376 0.371 0.322
## [2366] 0.338 0.350 0.667 0.364 0.267 0.294 0.000 0.000 0.000 0.000 0.000
## [2377] 0.000 0.000 0.000 0.478 0.400 0.420 0.441 0.313 0.283 0.252 0.440
## [2388] 0.348 0.315 0.303 0.143 0.000 0.000 0.000 0.000 0.526 0.478 0.407
## [2399] 0.408 0.230 0.368 0.333 0.333 0.456 0.371 0.308 0.375 0.250 0.333
## [2410] 0.232 0.219 0.182 0.235 0.229 0.139 0.091 0.059 0.000 0.000 0.000
## [2421] 0.000 0.000 0.362 0.328 0.366 0.294 0.312 0.500 0.612 0.333 0.324
## [2432] 0.250 0.231 0.233 0.253 0.192 0.294 0.000 0.000 0.000 0.000 0.798
## [2443] 0.398 0.390 0.376 0.439 0.311 0.395 0.386 0.360 0.347 0.329 0.273
## [2454] 0.267 0.167 0.000 0.000 0.000 0.517 0.719 0.600 0.468 0.376 0.400
## [2465] 0.375 0.667 1.250 1.000 1.000 0.456 0.400 0.413 0.475 0.179 0.125
## [2476] 0.000 0.000 0.000 0.605 0.719 0.413 0.377 0.303 0.331 0.500 0.412
## [2487] 0.506 0.718 0.506 0.250 0.351 0.341 0.214 0.200 0.167 0.167 0.219
## [2498] 0.200 0.000 0.000 0.475 0.482 0.648 0.484 0.466 0.462 0.530 0.500
## [2509] 0.441 0.435 0.635 0.368 0.428 0.469 0.405 0.526 0.510 0.440 0.417
## [2520] 0.399 0.349 0.458 0.402 0.494 0.458 0.427 0.320 0.439 0.390 0.391
## [2531] 0.443 0.417 0.381 0.402 0.375 0.298 0.398 0.397 0.378 0.409 0.413
## [2542] 0.433 0.368 0.336 0.333 0.360 0.362 0.301 0.387 0.362 0.382 0.393
## [2553] 0.309 0.416 0.284 0.303 0.259 0.282 0.313 0.310 0.344 0.290 0.248
## [2564] 0.311 0.325 0.299 0.296 0.295 0.339 0.313 0.248 0.317 0.244 2.000
## [2575] 0.600 0.500 0.571 0.500 0.714 0.600 0.565 0.478 0.741 0.333 0.300
## [2586] 0.400 0.370 0.295 0.491 0.319 0.357 0.286 0.333 0.459 0.373 0.517
## [2597] 0.273 0.370 0.400 0.392 0.372 0.344 0.417 0.250 0.250 0.250 0.243
## [2608] 0.241 0.241 0.269 0.231 0.421 0.318 0.227 0.227 0.347 0.222 0.219
## [2619] 0.250 0.276 0.386 0.209 0.250 0.286 0.200 0.400 0.200 0.227 0.238
## [2630] 0.250 0.237 0.184 0.195 0.227 0.182 0.178 0.246 0.167 0.333 0.192
## [2641] 0.154 0.242 0.150 0.185 0.143 0.233 0.167 0.444 0.097 0.083 0.037
## [2652] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [2663] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [2674] 0.000 0.000 0.000 0.000 0.569 0.576 0.608 0.493 0.574 0.430 0.565
## [2685] 0.419 0.459 0.462 0.384 0.519 0.543 0.420 0.425 0.424 0.417 0.470
## [2696] 0.416 0.431 0.422 0.421 0.471 0.417 0.510 0.469 0.527 0.354 0.390
## [2707] 0.404 0.370 0.505 0.392 0.344 0.383 0.378 0.408 0.414 0.397 0.346
## [2718] 0.411 0.434 0.371 0.348 0.386 0.434 0.348 0.317 0.274 0.312 0.381
## [2729] 0.283 0.286 0.338 0.405 0.240 0.243 0.233 0.212 1.000 0.542 0.500
## [2740] 1.000 0.500 0.444 0.580 0.563 0.414 0.385 0.487 0.423 0.506 0.415
## [2751] 0.455 0.378 0.600 0.417 0.500 0.333 0.330 0.511 0.411 0.375 0.423
## [2762] 0.429 0.333 0.296 0.278 0.323 0.318 0.318 0.318 0.385 0.367 0.316
## [2773] 0.309 0.368 0.316 0.333 0.375 0.250 0.250 0.295 0.424 0.394 0.396
## [2784] 0.298 0.333 0.333 0.265 0.269 0.359 0.308 0.410 0.271 0.320 0.224
## [2795] 0.269 0.268 0.393 0.273 0.282 0.211 0.211 0.388 0.204 0.385 0.333
## [2806] 0.192 0.219 0.324 0.289 0.217 0.438 0.250 0.185 0.250 0.318 0.227
## [2817] 0.182 0.235 0.235 0.222 0.167 0.250 0.167 0.167 0.211 0.153 0.133
## [2828] 0.125 0.111 0.100 0.091 0.087 0.077 0.074 0.000 0.000 0.000 0.000
## [2839] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [2850] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [2861] 0.000 0.000 0.000 0.000 0.000 0.000 0.451 0.497 0.477 0.401 0.505
## [2872] 0.443 0.394 1.000 0.500 0.423 0.424 0.581 0.407 0.360 0.341 0.222
## [2883] 0.261 0.091 0.000 0.000 0.000 0.532 0.471 0.445 0.368 0.340 0.409
## [2894] 0.346 0.391 0.400 0.429 0.356 0.500 0.298 0.446 0.111 0.000 0.000
## [2905] 0.000 0.458 0.408 0.435 0.323 0.336 0.392 0.286 0.293 0.288 0.289
## [2916] 0.257 0.185 0.273 0.143 0.000 0.000 0.000 0.000 0.500 0.211 0.100
## [2927] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.429
## [2938] 0.647 0.375 0.380 0.413 0.492 0.441 0.385 0.380 0.310 0.308 0.349
## [2949] 0.239 0.000 0.000 0.000 0.000 0.000    NA 0.537 0.434 0.399 0.473
## [2960] 0.455 0.298 0.294 1.000 1.667 0.500 0.500 0.472 0.441 0.353 0.417
## [2971] 0.394 0.301 0.430 0.000 0.000 0.000 0.563 0.451 0.481 0.368 0.422
## [2982] 0.400 0.333 0.380 0.356 0.375 0.345 0.257 0.200 0.333 0.375 0.000
## [2993] 0.435 0.553 0.389 0.379 0.428 0.346 0.377 0.260 0.321 0.320 0.271
## [3004] 0.244 0.400 0.208 0.188 0.167 0.100 0.000 0.000 0.000 0.000 0.000
## [3015] 0.000 0.523 0.469 0.467 0.394 0.409 0.339 0.259 0.369 0.308 0.406
## [3026] 0.226 0.235 0.222 0.222 0.125 0.100 0.000 0.422 0.411 0.410 0.439
## [3037] 0.336 0.289 0.358 0.271 0.333 0.214 0.250 0.167 0.125 0.000 0.000
## [3048] 0.000 0.000
```

```
## Warning in Ops.factor(FullHit$ob.., FullHit$slg..): '+' not meaningful for
## factors
```

<table class="table table-striped table-hover" style="font-size: 12px; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Player </th>
   <th style="text-align:left;"> Team </th>
   <th style="text-align:left;"> AVG </th>
   <th style="text-align:right;"> HR </th>
   <th style="text-align:right;"> wOBA </th>
   <th style="text-align:right;"> wRAA </th>
   <th style="text-align:right;"> wRC </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Bryce Rheault </td>
   <td style="text-align:left;"> BVU </td>
   <td style="text-align:left;"> 0.399 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 0.277 </td>
   <td style="text-align:right;"> 11.646 </td>
   <td style="text-align:right;"> 47.890 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Truman Schmitt </td>
   <td style="text-align:left;"> SIM </td>
   <td style="text-align:left;"> 0.39 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 0.311 </td>
   <td style="text-align:right;"> 11.422 </td>
   <td style="text-align:right;"> 37.720 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Garrett Saunders </td>
   <td style="text-align:left;"> CEN </td>
   <td style="text-align:left;"> 0.361 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 0.276 </td>
   <td style="text-align:right;"> 9.387 </td>
   <td style="text-align:right;"> 38.719 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Luke Plunkett    </td>
   <td style="text-align:left;"> LUT </td>
   <td style="text-align:left;"> 0.352 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 0.282 </td>
   <td style="text-align:right;"> 8.638 </td>
   <td style="text-align:right;"> 34.093 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Derek Kolbush </td>
   <td style="text-align:left;"> NWU </td>
   <td style="text-align:left;"> 0.354 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 0.272 </td>
   <td style="text-align:right;"> 7.929 </td>
   <td style="text-align:right;"> 34.058 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Jordan Kaplan   </td>
   <td style="text-align:left;"> COE </td>
   <td style="text-align:left;"> 0.333 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 0.249 </td>
   <td style="text-align:right;"> 7.614 </td>
   <td style="text-align:right;"> 41.161 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Kellen Mitchell    </td>
   <td style="text-align:left;"> DBQ </td>
   <td style="text-align:left;"> 0.347 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0.266 </td>
   <td style="text-align:right;"> 7.583 </td>
   <td style="text-align:right;"> 34.049 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Kevin DeLaney   </td>
   <td style="text-align:left;"> COE </td>
   <td style="text-align:left;"> 0.344 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0.244 </td>
   <td style="text-align:right;"> 7.572 </td>
   <td style="text-align:right;"> 43.311 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Tyler Hovick   </td>
   <td style="text-align:left;"> WAR </td>
   <td style="text-align:left;"> 0.333 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 0.270 </td>
   <td style="text-align:right;"> 7.027 </td>
   <td style="text-align:right;"> 30.628 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Jacob Burns   </td>
   <td style="text-align:left;"> COE </td>
   <td style="text-align:left;"> 0.366 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0.249 </td>
   <td style="text-align:right;"> 6.997 </td>
   <td style="text-align:right;"> 37.678 </td>
  </tr>
</tbody>
</table>
Another statistic that showcases our successful offensive season is wRC (weighted runs created). Developed by Tom Tango, weighted runs created credits a player for their total offensive production over a season. This stat can be viewed as the ``raw number" version of wRAA. Coe had 4 players in the top-10 in 2019. For comparison, Coe had 4 regular players with a below average wRAA in 2018, and 5 regulars hitting below .250.

3 out of the remaining 4 regular starters starters (Arp, LeGrand and Berger) were in the top 30 - all with at least 30 wRC. Frazier (20) and Evans (17) combined for 37 wRC in 163 at-bats in center field, as they essentially split time. Henry had 18 wRC for the 75% of games he started at third.

An impressive aspect of our offensive success in 2019 was that it was not a result of a substantial increase in power output. The plot below shows that our .104 ISO (isolated power) predicts us to be average or even slightly below average in terms of weighted runs above average. We tended to manufacture runs with an abundance of singles and the occasional extra base-hit. Our 398 singles were the most in the BBCOR era. A good representation of this was the 15-2 victory over Luther on April 16th in which we had 20 hits, 18 singles, and 2 strikeouts.

![](CoeBaseball2019Review_files/figure-html/unnamed-chunk-3-1.png)<!-- -->

2019 was easily the best pitching performance from a Coe College pitching staff since 2001. A 2.74 ERA that ranked 3rd nationally was better than our next best year, 2015, by .79 runs. In a season in which the 2015 team almost mirrored the 2019 offensive output, the recent pitching was far superior. We also posted our best strikeout rate since 2001 (24.6%) and this was the third best in conference history -- only behind 2014 Buena Vista (28.9%) and 2012 Wartburg (25.2%). We averaged a 15.05% K-rate from 2011-2016, with growth to 19.14% in 2017 and 19.76% in 2018 before last season's monumental jump. When combined with the 3rd best walk rate in the conference, it was a recipe for success, evidenced by the 8th best ratio in the era. In 2018, we had our worst walk rate since 2006 (12.32%) and responded with more than a 3% improvement. Another improvement in 2020 should be an expectation given the experience we will have on the mound once again. While Dubuque was able to do a great job limiting walks throughout the 2019 season, it did not translate well enough to run prevention given their offensive output.

<table class="table table-striped table-hover" style="font-size: 12px; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> Year </th>
   <th style="text-align:left;"> Team </th>
   <th style="text-align:right;"> ERA </th>
   <th style="text-align:right;"> K% </th>
   <th style="text-align:right;"> BB% </th>
   <th style="text-align:right;"> K:BB </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 2018 </td>
   <td style="text-align:left;"> DBQ </td>
   <td style="text-align:right;"> 3.39 </td>
   <td style="text-align:right;"> 20.99 </td>
   <td style="text-align:right;"> 5.63 </td>
   <td style="text-align:right;"> 3.73 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2019 </td>
   <td style="text-align:left;"> DBQ </td>
   <td style="text-align:right;"> 4.07 </td>
   <td style="text-align:right;"> 24.09 </td>
   <td style="text-align:right;"> 6.84 </td>
   <td style="text-align:right;"> 3.52 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2017 </td>
   <td style="text-align:left;"> DBQ </td>
   <td style="text-align:right;"> 3.95 </td>
   <td style="text-align:right;"> 20.53 </td>
   <td style="text-align:right;"> 5.99 </td>
   <td style="text-align:right;"> 3.43 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2013 </td>
   <td style="text-align:left;"> WAR </td>
   <td style="text-align:right;"> 3.70 </td>
   <td style="text-align:right;"> 21.52 </td>
   <td style="text-align:right;"> 6.96 </td>
   <td style="text-align:right;"> 3.09 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2017 </td>
   <td style="text-align:left;"> WAR </td>
   <td style="text-align:right;"> 3.12 </td>
   <td style="text-align:right;"> 23.25 </td>
   <td style="text-align:right;"> 7.86 </td>
   <td style="text-align:right;"> 2.96 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2016 </td>
   <td style="text-align:left;"> WAR </td>
   <td style="text-align:right;"> 3.53 </td>
   <td style="text-align:right;"> 19.21 </td>
   <td style="text-align:right;"> 6.54 </td>
   <td style="text-align:right;"> 2.94 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2014 </td>
   <td style="text-align:left;"> BVU </td>
   <td style="text-align:right;"> 2.64 </td>
   <td style="text-align:right;"> 28.87 </td>
   <td style="text-align:right;"> 10.62 </td>
   <td style="text-align:right;"> 2.72 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2019 </td>
   <td style="text-align:left;"> COE </td>
   <td style="text-align:right;"> 2.74 </td>
   <td style="text-align:right;"> 24.55 </td>
   <td style="text-align:right;"> 9.22 </td>
   <td style="text-align:right;"> 2.66 </td>
  </tr>
</tbody>
</table>

Coe had by far the best opponents batting average in the ARC at .224 that was the 2nd best since 2001, only trailing Buena Vista in 2014 by one point. The 2019 pitching staff was one of only 8 to post a sub-.250 batting average against over a season in conference history. Where we didn't have the K:BB that ratio that Dubuque did, we made up with generating consistent soft contact. Buena Vista was second in BAA at .251.

An issue in 2017 and 2018 was hit-by-pitches from our pitchers, ranking second-worst in the conference each season, with 58 and 59 respectively. In 2019, that total dropped to 37 which was third-best in the ARC. Buena Vista had a conference record 73 last season.

The individual stats from our pitching staff make understanding our success a lot easier. According to FIP (fielding independent pitching), measuring what a player’s ERA would look like over a given period of time if the pitcher were to have experienced league average results on balls in play and league average timing, Coe had 5 of the conference's top-10 qualified pitchers and 6 of the top-20. Table 5 ranks the pitchers FIPs that pitched at least 15 innings in 2019. Out of those 6, FIP tells us that conference pitcher of the year, Zach Kammin, was the worst of the group.


```
## 
## Call:
## lm(formula = ra ~ hr + bb + so, data = TpitchingIIAC)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -73.793 -21.320  -5.531  20.282  93.134 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 133.94665   17.45938   7.672 1.72e-12 ***
## hr            2.51239    0.32947   7.626 2.23e-12 ***
## bb            0.69739    0.10488   6.649 4.69e-10 ***
## so           -0.17289    0.05195  -3.328  0.00109 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 31.09 on 156 degrees of freedom
## Multiple R-squared:  0.4912,	Adjusted R-squared:  0.4814 
## F-statistic: 50.19 on 3 and 156 DF,  p-value: < 2.2e-16
```

```
## 
## Call:
## lm(formula = ra ~ hr + bb + so + X1b + X2b + X3b + hbp, data = TpitchingIIAC)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -41.185 -12.297  -0.278  10.716  50.602 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -37.79494   14.73458  -2.565   0.0113 *  
## hr            2.14334    0.19915  10.762  < 2e-16 ***
## bb            0.43199    0.06420   6.729 3.27e-10 ***
## so           -0.21091    0.03037  -6.944 1.04e-10 ***
## X1b           0.46024    0.04683   9.829  < 2e-16 ***
## X2b           0.97233    0.13008   7.475 5.69e-12 ***
## X3b           1.94288    0.35357   5.495 1.61e-07 ***
## hbp           0.35631    0.15032   2.370   0.0190 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 17.66 on 152 degrees of freedom
## Multiple R-squared:  0.8401,	Adjusted R-squared:  0.8327 
## F-statistic: 114.1 on 7 and 152 DF,  p-value: < 2.2e-16
```

![](CoeBaseball2019Review_files/figure-html/unnamed-chunk-5-1.png)<!-- --><table class="table table-striped table-hover" style="font-size: 12px; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Player </th>
   <th style="text-align:left;"> Team </th>
   <th style="text-align:right;"> IP </th>
   <th style="text-align:right;"> SO </th>
   <th style="text-align:right;"> BB </th>
   <th style="text-align:right;"> ERA </th>
   <th style="text-align:right;"> FIP </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Chase Kueter </td>
   <td style="text-align:left;"> DBQ </td>
   <td style="text-align:right;"> 94.2 </td>
   <td style="text-align:right;"> 116 </td>
   <td style="text-align:right;"> 16 </td>
   <td style="text-align:right;"> 2.95 </td>
   <td style="text-align:right;"> 0.02 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Colin Coffey </td>
   <td style="text-align:left;"> LUT </td>
   <td style="text-align:right;"> 78.1 </td>
   <td style="text-align:right;"> 57 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 2.53 </td>
   <td style="text-align:right;"> 0.07 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Riley LeGrand </td>
   <td style="text-align:left;"> COE </td>
   <td style="text-align:right;"> 22.0 </td>
   <td style="text-align:right;"> 21 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 4.50 </td>
   <td style="text-align:right;"> 0.14 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> TJ Deardorff </td>
   <td style="text-align:left;"> COE </td>
   <td style="text-align:right;"> 43.0 </td>
   <td style="text-align:right;"> 38 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 1.05 </td>
   <td style="text-align:right;"> 0.38 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Aaron Eybers </td>
   <td style="text-align:left;"> WAR </td>
   <td style="text-align:right;"> 39.2 </td>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 3.86 </td>
   <td style="text-align:right;"> 0.41 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> TJ Johnson </td>
   <td style="text-align:left;"> COE </td>
   <td style="text-align:right;"> 24.2 </td>
   <td style="text-align:right;"> 13 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 1.46 </td>
   <td style="text-align:right;"> 0.45 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Andrew Schmit </td>
   <td style="text-align:left;"> COE </td>
   <td style="text-align:right;"> 65.0 </td>
   <td style="text-align:right;"> 61 </td>
   <td style="text-align:right;"> 15 </td>
   <td style="text-align:right;"> 2.63 </td>
   <td style="text-align:right;"> 0.57 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Jordan Nelson </td>
   <td style="text-align:left;"> DBQ </td>
   <td style="text-align:right;"> 65.1 </td>
   <td style="text-align:right;"> 52 </td>
   <td style="text-align:right;"> 16 </td>
   <td style="text-align:right;"> 3.31 </td>
   <td style="text-align:right;"> 0.61 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Jack Greene </td>
   <td style="text-align:left;"> COE </td>
   <td style="text-align:right;"> 79.1 </td>
   <td style="text-align:right;"> 82 </td>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:right;"> 3.18 </td>
   <td style="text-align:right;"> 0.64 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Nathan Schwanke </td>
   <td style="text-align:left;"> CEN </td>
   <td style="text-align:right;"> 19.1 </td>
   <td style="text-align:right;"> 19 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 2.33 </td>
   <td style="text-align:right;"> 0.68 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Nick Long </td>
   <td style="text-align:left;"> CEN </td>
   <td style="text-align:right;"> 56.2 </td>
   <td style="text-align:right;"> 52 </td>
   <td style="text-align:right;"> 16 </td>
   <td style="text-align:right;"> 4.29 </td>
   <td style="text-align:right;"> 0.75 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Gage Smart </td>
   <td style="text-align:left;"> BVU </td>
   <td style="text-align:right;"> 47.1 </td>
   <td style="text-align:right;"> 54 </td>
   <td style="text-align:right;"> 13 </td>
   <td style="text-align:right;"> 1.14 </td>
   <td style="text-align:right;"> 0.77 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Egan Bonde </td>
   <td style="text-align:left;"> BVU </td>
   <td style="text-align:right;"> 72.2 </td>
   <td style="text-align:right;"> 35 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 3.10 </td>
   <td style="text-align:right;"> 0.83 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Tyler Carlson </td>
   <td style="text-align:left;"> DBQ </td>
   <td style="text-align:right;"> 40.1 </td>
   <td style="text-align:right;"> 29 </td>
   <td style="text-align:right;"> 11 </td>
   <td style="text-align:right;"> 4.46 </td>
   <td style="text-align:right;"> 0.87 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Rece Martin </td>
   <td style="text-align:left;"> CEN </td>
   <td style="text-align:right;"> 39.2 </td>
   <td style="text-align:right;"> 52 </td>
   <td style="text-align:right;"> 18 </td>
   <td style="text-align:right;"> 4.08 </td>
   <td style="text-align:right;"> 0.88 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Nick Sewruk </td>
   <td style="text-align:left;"> DBQ </td>
   <td style="text-align:right;"> 52.0 </td>
   <td style="text-align:right;"> 36 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 4.67 </td>
   <td style="text-align:right;"> 0.93 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Joey Cardamon </td>
   <td style="text-align:left;"> LUT </td>
   <td style="text-align:right;"> 73.1 </td>
   <td style="text-align:right;"> 56 </td>
   <td style="text-align:right;"> 19 </td>
   <td style="text-align:right;"> 3.07 </td>
   <td style="text-align:right;"> 1.01 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Ryan Riddle </td>
   <td style="text-align:left;"> CEN </td>
   <td style="text-align:right;"> 21.0 </td>
   <td style="text-align:right;"> 26 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 1.29 </td>
   <td style="text-align:right;"> 1.04 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Zach Kammin </td>
   <td style="text-align:left;"> COE </td>
   <td style="text-align:right;"> 77.1 </td>
   <td style="text-align:right;"> 77 </td>
   <td style="text-align:right;"> 28 </td>
   <td style="text-align:right;"> 2.68 </td>
   <td style="text-align:right;"> 1.07 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Ethan Peters </td>
   <td style="text-align:left;"> LOR </td>
   <td style="text-align:right;"> 18.0 </td>
   <td style="text-align:right;"> 12 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 4.00 </td>
   <td style="text-align:right;"> 1.14 </td>
  </tr>
</tbody>
</table>
This tells us that in 375 innings pitched by our pitchers in 2019, 62.4% of those were thrown by a top-10 pitcher in the conference and 83% of those were thrown by a top-20 pitcher. As table 5 also shows, neither Simpson nor Nebraska Wesleyan had a top-20 pitcher. Wartburg and Loras only had 1 -- neither of whom were regular starting pitchers.

Other takeaways from Table 5 are that Riley LeGrand seems too high and All-American Gage Smart and ARC Pitcher of the Year Zach Kammin seem too low. BABIP is a good metric to look at and it tells us that LeGrand had the third highest BABIP among qualified pitchers at .412. Smart had the lowest BABIP at .171 and Kammin  had the 7th-lowest at .273. As addressed in the hitting section, BABIP extremes on either side of the spectrum can be as a result of the defense behind you, luck, or pure talent level. When looking at those with the best 2019 BABIPs in the ARC, you see the names Smart, Tyrel Johnson, Deardorff, Schneiderman, and Kammin -- pitchers who are known to have some of the best pure stuff to generate consistent weak contact. This is where xFIP (expected fielding independent pitching) will come in handy in the future. Thus, FIP can be used as a better measure of success than ERA, but it still has its limitations in this context. 

Finally, we were 29-2 when leading after the 6th inning throughout 2019 and 8-1 in one-run games. FIP also tells us that we had 3 of the top-5 relief pitchers in LeGrand, Deardorff, & Johnson. We were able to keep the same effectiveness on the mound from game-to-game after we pulled our starter, truly setting us apart.



